export const UPDATE_GAME_NUM = 'UPDATE_GAME_NUM';
export const RESTART_GAME_NUM = 'RESTART_GAME_NUM';
export const CLICK_MOVE_UP = 'CLICK_MOVE_UP';
export const CLICK_MOVE_DOWN = 'CLICK_MOVE_DOWN';
export const CLICK_MOVE_LEFT = 'CLICK_MOVE_LEFT';
export const CLICK_MOVE_RIGHT = 'CLICK_MOVE_RIGHT';
export const CHANGE_STATUS = 'CHANGE_STATUS';
