export const FETCH_HOMEWORK_INFO = 'FETCH_HOMEWORK_INFO';
export const FETCH_HOMEWORK_INFO_SUC = 'FETCH_HOMEWORK_INFO_SUC';
export const FETCH_HOMEWORK_INFO_FAI = 'FETCH_HOMEWORK_INFO_FAI';
export const CHANGE_WORK_STAUS = 'CHANGE_WORK_STAUS';
export const FILTER_STUDENT = 'FILTER_STUDENT';