export const FETCH_HOMEWORK_UNREVIEW_INFO = 'FETCH_HOMEWORK_UNREVIEW_INFO';
export const FETCH_HOMEWORK_UNREVIEW_INFO_SUC = 'FETCH_HOMEWORK_UNREVIEW_INFO_SUC';
export const FETCH_HOMEWORK_UNREVIEW_INFO_FAI = 'FETCH_HOMEWORK_UNREVIEW_INFO_FAI';

export const FETCH_HOMEWORK_REVIEWED_INFO = 'FETCH_HOMEWORK_REVIEWED_INFO';
export const FETCH_HOMEWORK_REVIEWED_INFO_SUC = 'FETCH_HOMEWORK_REVIEWED_INFO_SUC';
export const FETCH_HOMEWORK_REVIEWED_INFO_FAI = 'FETCH_HOMEWORK_REVIEWED_INFO_FAI';


export const FETCH_HOMEWORK_ALLUNREVIEW_INFO = 'FETCH_HOMEWORK_ALLUNREVIEW_INFO';
export const FETCH_HOMEWORK_ALLUNREVIEW_INFO_SUC = 'FETCH_HOMEWORK_ALLUNREVIEW_INFO_SUC';
export const FETCH_HOMEWORK_ALLUNREVIEW_INFO_FAI = 'FETCH_HOMEWORK_ALLUNREVIEW_INFO_FAI';


export const FETCH_HOMEWORK_ALLREVIEWED_INFO = 'FETCH_HOMEWORK_ALLREVIEWED_INFO';
export const FETCH_HOMEWORK_ALLREVIEWED_INFO_SUC = 'FETCH_HOMEWORK_ALLREVIEWED_INFO_SUC';
export const FETCH_HOMEWORK_ALLREVIEWED_INFO_FAI = 'FETCH_HOMEWORK_ALLREVIEWED_INFO_FAI';






export const CHANGE_HOMEWORK_STAUS = 'CHANGE_HOMEWORK_STAUS';
export const FILTER_HOMEWORK_ITEM = 'FILTER_HOMEWORK_ITEM';
export const CHANGE_REJECT_STATUS = 'CHANGE_REJECT_STATUS';
export const SEND_REVIEW = 'SEND_REVIEW';